# -*- coding: utf-8 -*-
"""
Project: Multimodal Medical AI Microservice - End-to-End Inference Engine
Tech Stack: FastAPI + HTTPX + Ollama / OpenRouter (vision-language models)

This service provides a secure RESTful API endpoint that accepts user-uploaded medical
images (e.g., X-rays) and diagnostic prompts, and asynchronously interacts with the
local Ollama container to produce multimodal diagnostic reports.
"""

import base64
import logging
from io import BytesIO
from PIL import Image
from fastapi import FastAPI, UploadFile, File, Form, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware

from inference import generate_medical_report

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("medical-vlm-service")

# Initialize FastAPI application
app = FastAPI(
	title="Multimodal Medical AI Image Dialogue Microservice (MVP)",
	description="Low-latency image diagnosis API based on Llama-3.2-Vision and Ollama",
	version="1.0.0"
)

# Enable CORS (Cross-Origin Resource Sharing) for future frontend integration
app.add_middleware(
	CORSMiddleware,
	allow_origins=["*"],  # In production, domains should be strictly restricted
	allow_credentials=True,
	allow_methods=["*"],
	allow_headers=["*"],
)

# Define medical-specific system prompt to constrain model behavior
SYSTEM_PROMPT = """
# Role
You are a senior radiologist with 20 years of clinical experience. Respond in an objective, rigorous, and medically logical tone.

# Defense Rules
* **Strict Modality Restriction**: Upon receiving an image, you must first verify whether it is a compliant medical X-ray image. If the image is non-medical (e.g., personal photos, landscapes, pet photos, or cartoons), you are strictly prohibited from performing any medical analysis and must respond uniformly with: "[Error] The uploaded file does not comply with medical imaging standards. Please re-upload a correct radiology X-ray image."
* **Resolution and Quality Baseline**: You must assess the clarity of the image. If the image resolution is too low, extremely blurry, excessively noisy, or of such poor quality that basic anatomical structures cannot be identified, you must refuse to perform substantive inference and respond uniformly with: "[Error] Image clarity is insufficient and resolution is too poor for analysis. Please provide a high-resolution image."

# Task
* 📋 **Core Mission**: Once the uploaded image successfully passes the defense rule validation, you must perform a systematic and comprehensive analysis of the medical image following the clinical reasoning of a radiology specialist. You must strictly adhere to the "Report Structure" specified below for Markdown-formatted output, and must not merge or omit any sections.

## Report Structure
1. **Image Quality Assessment**: Evaluate the image acquisition quality, contrast, and anatomical structure completeness, and clearly state whether the image meets clinical diagnostic standards.
2. **Objective Findings**: Carefully observe and list all abnormal features found in the image (e.g., lesion size, morphological appearance, specific anatomical location, and boundary clarity). Provide only objective descriptions here; do not make specific pathological diagnoses.
3. **Impression**: Combine the objective findings above and apply medical logic for inductive analysis to propose the most likely preliminary diagnostic inferences or differential diagnoses.
4. **Recommendations & Disclaimer**: Provide professional recommendations for subsequent clinical management or further imaging examinations. Finally, you must include the disclaimer: "This report was generated by an AI-assisted system and is for clinical reference only. Final diagnosis should be determined by a licensed physician."
"""

def preprocess_and_compress_image(image_bytes: bytes, max_size: int = 1120, quality: int = 80) -> bytes:
    """
    To resolve JSON stream truncation issues caused by oversized single requests at the external API gateway.
    Proportionally scale large images to the optimal edge length for Llama-3.2-Vision (1120px) and limit size to a safe range.
    """
    try:
        img = Image.open(BytesIO(image_bytes))
        
        # Convert to standard RGB (prevent encoding incompatibility from special color gamuts or grayscale modes in medical images)
        if img.mode != "RGB":
            img = img.convert("RGB")
            
        width, height = img.size
        
        # Perform proportional scaling
        if width > max_size or height > max_size:
            if width > height:
                new_width = max_size
                new_height = int(height * (max_size / width))
            else:
                new_height = max_size
                new_width = int(width * (max_size / height))
            
            # Use high-quality LANCZOS filter to preserve edge details in radiology images
            img = img.resize((new_width, new_height), Image.Resampling.LANCZOS)
            logger.info(f"Image size successfully downsampled from {width}x{height} to {new_width}x{height}")
            
        # Output compressed binary stream
        output = BytesIO()
        img.save(output, format="JPEG", quality=quality)
        return output.getvalue()
    except Exception as e:
        logger.error(f"Image defensive preprocessing pipeline failed: {str(e)}")
        raise ValueError(f"Image preprocessing failed: {str(e)}")

@app.post("/analyze")
async def analyze_medical_image(
    prompt: str = Form(...),
    image: UploadFile = File(...)
):
    try:
        # 1. Asynchronously read image raw binary data and convert to Base64 string
        image_bytes = await image.read()
        base64_image = base64.b64encode(image_bytes).decode("utf-8")
        
        # 2. Call environment routing module (auto-detects local for OpenRouter, dev for Ollama)
        logger.info("Dispatching multimodal core for medical image report generation...")
        report_content = await generate_medical_report(base64_image, prompt, SYSTEM_PROMPT)
        
        # 3. Return structured report
        return {"report": report_content}
        
    except Exception as e:
        logger.error(f"Unexpected error in inference pipeline: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Internal server error: {str(e)}"
        )
